---
apiVersion: v1
kind: Service
metadata:
  name: kafka-topics-ui
  labels:
    app: kafka-topics-ui
    release: kafka-topics-ui
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: kafka-topics-ui
    release: kafka-topics-ui
---
# Source: kafka-topics-ui/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-topics-ui
  labels:
    app: kafka-topics-ui
    release: kafka-topics-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-topics-ui
      release: kafka-topics-ui
  template:
    metadata:
      labels:
        app: kafka-topics-ui
        release: kafka-topics-ui
    spec:
      containers:
        - name: kafka-topics-ui
          image: "landoop/kafka-topics-ui:0.9.4"
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_REST_PROXY_URL
              value: "http://confluent-platform-cp-kafka-rest:8082"
            - name: PROXY
              value: "true"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
