---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry-ui
  labels:
    app: schema-registry-ui
    release: schema-registry-ui
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: schema-registry-ui
    release: schema-registry-ui
---
# Source: schema-registry-ui/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry-ui
  labels:
    app: schema-registry-ui
    release: schema-registry-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry-ui
      release: schema-registry-ui
  template:
    metadata:
      labels:
        app: schema-registry-ui
        release: schema-registry-ui
    spec:
      containers:
        - name: schema-registry-ui
          image: "landoop/schema-registry-ui:0.9.5"
          imagePullPolicy: IfNotPresent
          env:
            - name: SCHEMAREGISTRY_URL
              value: "http://confluent-platform-cp-schema-registry:8081"
            - name: PROXY
              value: "true"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
