---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: fluentd
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: fluentd
    namespace: kube-system

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      containers:
        - name: fluent-kafka
          image: fluent/fluentd-kubernetes-daemonset:v1.11.1-debian-kafka-1.0
          env:
            - name: FLUENT_KAFKA_TAG
              value: kubernetes.var.log.containers.twitter-reader-**
            - name: FLUENT_KAFKA_BROKERS
              value: confluent-platform-cp-kafka-headless.default.svc.cluster.local:9092
            - name: FLUENT_KAFKA_DEFAULT_TOPIC
              value: twitter.sampled-stream
            - name: # systemd not exists in linuxkit (docker for mac host)
                FLUENTD_SYSTEMD_CONF
              value: disable
            - name: FLUENT_KAFKA_MAX_SEND_LIMIT_BYTES
              value: "10240"
            - name: FLUENTD_PROMETHEUS_CONF
              value: disable
            - name: FLUENTD_CONF
              value: fluent-kafka.conf
          resources:
            limits:
              memory: 1G
            requests:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - name: config
              mountPath: /fluentd/etc/
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: fluent-kafka-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
