apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  name: ingress-spark-ui
spec:
  rules:
    - host: spark-ui.localhost
      http:
        paths:
          - backend:
              serviceName: spark-pi-ui-svc
              servicePort: 4040
