# To use this docker registry on docker for mac,
# you must configure "docker.for.mac.localhost:5000" as "insecure-registries" in "Daemon" tab of "Preferences".
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: registry-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry-container
          image: registry:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: kube-system
spec:
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
