apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  name: presto-ingress
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: presto
              servicePort: 8080
