apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  name: ingress-minio
spec:
  rules:
    - host: minio.localhost
      http:
        paths:
          - backend:
              serviceName: minio
              servicePort: 9000
