---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-ui
  labels:
    app: kafka-connect-ui
    release: kafka-connect-ui
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: kafka-connect-ui
    release: kafka-connect-ui
---
# Source: kafka-connect-ui/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect-ui
  labels:
    app: kafka-connect-ui
    release: schema-registry-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect-ui
      release: kafka-connect-ui
  template:
    metadata:
      labels:
        app: kafka-connect-ui
        release: kafka-connect-ui
    spec:
      containers:
        - name: kafka-connect-ui
          image: "landoop/kafka-connect-ui:0.9.7"
          imagePullPolicy: IfNotPresent
          env:
            - name: CONNECT_URL
              value: "http://confluent-platform-cp-kafka-connect:8083"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
